# 3 dots (...) and pass mean the same thing

class DataIngestionConfig:
    pass
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...